from enum import Enum

class CRIME_TYPE(Enum):
    KIDNAPPING = "KIDNAPPING",
    ROBBERY = "ROBBERY",
    SEXUAL_ASSAULT = "SEXUAL_ASSAULT",
    THEFT = "THEFT",
    BURGLARY = "BURGLARY",
    VEHICLE_THEFT = "VEHICLE_THEFT",
    ARSON = "ARSON",
    CRIMINAL_TRESPASS = "CRIMINAL_TRESPASS",
    WEAPONS_OFFENSE = "WEAPONS_OFFENSE",
    DRUG_OFFENSE = "DRUG_OFFENSE",
    PUBLIC_ORDER_OFFENSE = "PUBLIC_ORDER_OFFENSE",
    PUBLIC_PEACE_OFFENSE = "PUBLIC_PEACE_OFFENSE",
    ASSAULT = "ASSAULT",
    CRIMINAL_DAMAGE = "CRIMINAL_DAMAGE",
    BATTERY = "BATTERY",
    HOMICIDE = "HOMICIDE",
    PROSTITUTION = "PROSTITUTION",
    GAMBLING = "GAMBLING",
    STALKING = "STALKING",
    OTHER = "OTHER"